#!/bin/sh -x
prefix=/usr/local
rm -rf ${prefix}/include/ocropus
rm -rf ${prefix}/lib/libocropus.*
rm -rf ${prefix}/bin/ocropus

# FIXME clean up mess from bad autoconf install
((cd include; ls *.h); (cd ocr-utils; ls *.h)) |
while read header; do
    rm -rf ${prefix}/include/$header
done
